# Generated by Django 3.1.1 on 2020-09-22 14:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('hero_simple', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True)), ('button_1_text', wagtail.core.blocks.CharBlock(help_text='Add Button 1 text', required=False)), ('button_1_link', wagtail.core.blocks.URLBlock(help_text='Where will button 1 go?', required=False)), ('button_2_text', wagtail.core.blocks.CharBlock(help_text='Add Button 2 text', required=False)), ('button_2_link', wagtail.core.blocks.URLBlock(help_text='Where will button 2 go?', required=False)), ('background_color', wagtail.core.blocks.CharBlock(help_text='What color will the background be?', required=True)), ('text_color', wagtail.core.blocks.CharBlock(help_text='What color will be text be?', required=True))]))], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Flex Page',
                'verbose_name_plural': 'Flex Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
