# Generated by Django 3.1.2 on 2020-10-13 13:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_auto_20200922_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('hero_simple', wagtail.core.blocks.StructBlock([('section_id', wagtail.core.blocks.CharBlock(help_text='Add your section #id', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title.', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text.', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Please choose a Hero image.', required=False)), ('button_1_text', wagtail.core.blocks.CharBlock(help_text='Add Button 1 text', required=False)), ('button_1_link', wagtail.core.blocks.URLBlock(help_text='Where will button 1 go?', required=False)), ('button_2_text', wagtail.core.blocks.CharBlock(help_text='Add Button 2 text', required=False)), ('button_2_link', wagtail.core.blocks.URLBlock(help_text='Where will button 2 go?', required=False))])), ('about_us', wagtail.core.blocks.StructBlock([('section_id', wagtail.core.blocks.CharBlock(help_text='Add your section #id', label='Block ID', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title.', label='Title', required=True)), ('column1text', wagtail.core.blocks.RichTextBlock(help_text='Add text for column 1.', label='Column 1', required=False)), ('column2text', wagtail.core.blocks.RichTextBlock(help_text='Add text for column 2.', label='Column 2', required=False)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Add Button 1 text', label='Button Text', required=False)), ('button_link', wagtail.core.blocks.URLBlock(help_text='Where will button 1 go?', required=False))]))], blank=True, null=True),
        ),
    ]
